language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
matrix:
  include:
    - python: 2.7
      env: TOXENV=docs
sudo: false
install:
  - pip install tox-travis
  - npm install -g grunt-cli bower
  - npm install
  - grunt build
script:
  - tox
  
branches:
  only:
  - master
