language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
matrix:
  include:
    - python: 2.7
      env: TOXENV=docs
install:
  - pip install tox-travis
script:
  - tox
  
branches:
  only:
  - master
