version: 2.1

commands:
  run-tox:
    description: "Run tox"
    parameters:
      version:
        type: string
      sphinx-version:
        type: string
        default: "16,17,18,20,21,22,23,24,30,31,32,33,34,35,40,41,latest"
    steps:
      - checkout
      - run: pip install --user tox
      - run: tox -e "<<parameters.version>>-sphinx{<<parameters.sphinx-version>>}"
  run-build:
    description: "Ensure built assets are up to date"
    steps:
      - checkout
      - setup_remote_docker
      # - run: npm ci
      - run: docker build -t sphinx_rtd_theme:latest .
      - run: docker run --cidfile=.container_id --mount type=bind,source="${CIRCLE_WORKING_DIRECTORY}/src",target=/project/src,readonly sphinx_rtd_theme:latest
      - run: docker cp "$(cat .container_id):/project/sphinx_rtd_theme" .
      - run: docker cp "$(cat .container_id):/project/package-lock.json" .
      - run:
          name: Ensure built assets are up to date
          command: |
            if [[ `git status sphinx_rtd_theme/ --porcelain` ]]
            then
              echo "ERROR: assets are out of date. Make sure to run 'npm run build' on your branch."
              git status sphinx_rtd_theme/ --porcelain
              exit 1
            fi

jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - run-build: {}
  py27:
    docker:
      - image: 'cimg/python:2.7'
    steps:
      - run-tox:
          version: py27
  py36:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - run-tox:
          version: py36
  py37:
    docker:
      - image: 'cimg/python:3.7'
    steps:
      - run-tox:
          version: py37
  py38:
    docker:
      - image: 'cimg/python:3.8'
    steps:
      - run-tox:
          version: py38
  py39:
    docker:
      - image: 'cimg/python:3.9'
    steps:
      - run-tox:
          version: py39

workflows:
  version: 2
  tests:
    jobs:
      - build
      - py39:
          requires:
            - build
      - py38:
          requires:
            - build
      - py37:
          requires:
            - build
      - py36:
          requires:
            - build
      - py27:
          requires:
            - build
